language: generic

env:
  global:
    - ENCRYPTION_LABEL="29c1cf4cf5c5"

script:
  - curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
